dist: trusty
sudo: false
language: generic
branches:
    only:
        master
script:
    - git config credential.helper "store --file=.git/credentials"
    - echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials 2>/dev/null
    - git config --global user.email "bhuvan.venkatesh21@gmail.com"
    - git config --global user.name "Bhuvan Venkatesh"
    - export NUM_RETRIES=3
    - export BUILD_TIME=120 #seconds
    - export CLONE_DIR=site
    - bash retry.sh

