dist: trusty
sudo: false
language: generic
branches:
  only: master
script:
- openssl aes-256-cbc -K $encrypted_817a849a5ddb_key -iv $encrypted_817a849a5ddb_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- export COMMITTER_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty='%cE')"
- export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty='%aN')"
- git config --global user.email $COMMITTER_EMAIL
- git config --global user.name $AUTHOR_NAME
- export NUM_RETRIES=3
- export BUILD_TIME=10
- export CLONE_DIR=site
- bash retry.sh
